CO-47: Add standard set of docker labels
cakesolutions/sbt-cake pull request #13
Opened 2017-05-26 13:10 UTC by carlpulley

- [ ] Add in generic set of labelling commands to BuildInfoPluginKeys
- [ ] Add in Docker specific container labelling
---
- [ ] Ready for Review

2017-05-26 13:25 UTC, amirkarimi approved these changes

2017-05-26 13:49 UTC, fommil commented
We need to make sure this don't break our live projects. We have some settings there we won't to migrate back. Let's do those before we introduce these changes.

2017-05-26 13:52 UTC, carlpulley commented
Please expand?

2017-05-26 13:57 UTC, fommil commented
I'm on holiday. Please hold off merging until I'm back on Tuesday so we can talk about it in detail.

2017-05-30 12:32 UTC, fommil commented on src/main/scala/net/cakesolutions/CakeDockerPlugin.scala
> +  private def imageLabels(containerName: String): Seq[Cmd] = {
this doesn't look like it will conflict with our existing project, but could you please explain what it could be used for?

2017-06-05 13:01 UTC, carlpulley commented on src/main/scala/net/cakesolutions/CakeDockerPlugin.scala
> +    dockerArgList
In order to reduce the Docker image size, we should simply generate a single `LABEL` here

2017-06-06 10:47 UTC, carlpulley commented on src/main/scala/net/cakesolutions/CakeDockerPlugin.scala
> +  private def imageLabels(containerName: String): Seq[Cmd] = {
This allows Docker images to be annotated with labels. In production environments, when we locate a docker image, we can then definitively trace its lineage without the need to infer anything.

2017-06-06 12:46 UTC, carlpulley commented on src/main/scala/net/cakesolutions/CakeBuildInfoPlugin.scala
> +  private def buildDockerVersion = "docker --version".!!.trim
We could do with ensuring that hostname, whoami, docker and git exist on the host machine

2017-06-06 16:09 UTC, lashford requested changes

2017-06-06 16:09 UTC, lashford commented on src/main/scala/net/cakesolutions/CakeBuildInfoPlugin.scala
> +    ("git branch" #| "grep *").!!.trim.drop(2)
don't really like this, how about `git symbolic-ref --short -q HEAD`

2017-06-06 16:21 UTC, lashford approved these changes

2017-06-06 16:21 UTC, merged