CO-13 Refactor Dependencies
cakesolutions/sbt-cake pull request #27
Opened 2017-07-05 15:41 UTC by amirkarimi

- [x] Refactor `build.sbt` dependencies and moved into `project/CakeDependencies.scala`
- [x] Refactor `project/plugins.sbt` dependencies and moved into `project/project/CakePluginDependencies.scala`
---
- [x] Ready for Review

2017-07-05 15:58 UTC, carlpulley requested changes

2017-07-05 15:58 UTC, carlpulley commented on build.sbt
> +addSbtPlugin(CakeDependencies.Sbt.dynver)
Lets import `CakeDependencies` at the top of this file?

2017-07-05 15:58 UTC, carlpulley commented on project/CakeDependencies.scala
> +object CakeDependencies {
For ease of searching, Lets place the top level val's and objects into alphabetical order

2017-07-05 15:58 UTC, carlpulley commented on project/CakeDependencies.scala
> +    private val version = "2.3.11"
Lets not make this private. That way we can potential use the version value in other code.

2017-07-05 16:00 UTC, carlpulley commented
I also note that we have some additional library dependencies in sbt-test - `find . -name "*.sbt" -exec grep -rn % {} \;` should locate the relevant files.

2017-07-05 16:01 UTC, carlpulley commented
Won't we also need to refactor library dependencies in CakePlatformPlugin.scala?

2017-07-05 16:07 UTC, carlpulley commented
Also, CakeBuildPlugin.scala has a few lines where `"org.scala-lang"` can be replaced by the more generic `scalaOrganization.value`.

2017-07-05 16:14 UTC, amirkarimi commented on build.sbt
> +addSbtPlugin(CakeDependencies.Sbt.dynver)
Then we'll get the following error as `Sbt` is also imported by another plugin:
```
error: reference to Sbt is ambiguous;
it is imported twice in the same scope by
import CakeDependencies._
and import _root_.com.lucidchart.sbt.scalafmt.ScalafmtSbtPlugin.autoImport._
```

2017-07-06 09:59 UTC, amirkarimi commented
@carlpulley 
> I also note that we have some additional library dependencies in sbt-test - find . -name "*.sbt" -exec grep -rn % {} \; should locate the relevant files.

All of them reference to `sbt-cake` and they're just single dependencies, except one which references to `akka-http-spray-json` and again is a single dependency. As they're separate projects, it doesn't make sense to me to refactor those single line dependencies into another file for each project. Or is there a better way?

> Won't we also need to refactor library dependencies in CakePlatformPlugin.scala?

`CakePlatformKeys` itself is just a list of dependencies. Though we can move it to a separate file.

2017-07-06 10:37 UTC, amirkarimi commented
>Also, CakeBuildPlugin.scala has a few lines where "org.scala-lang" can be replaced by the more generic scalaOrganization.value.
>
>A similar comment applies to project/plugins.sbt

The only place that `org.scala-lang` is used is [here](https://github.com/cakesolutions/sbt-cake/blob/master/src/main/scala/net/cakesolutions/CakeBuildPlugin.scala#L104-L114) which seems to be intentional.

2017-07-06 11:19 UTC, carlpulley commented on project/CakeDependencies.scala
> +  object Sbt {
If we place these `Sbt` dependencies in `CakePluginDependencies`, would we be able to access them in this context/scope?

2017-07-06 12:59 UTC, amirkarimi commented on project/CakeDependencies.scala
> +  object Sbt {
As far as I know we can't have access to objects defined in `project` folder (meta-build) in the main code (proper build) as we can't obtain the project name in the main code directly from `build.sbt`. If it's true, the same rule applies here; the context of `/project/project/CakePluginDependencies.scala` is different than the files in `/project`.

2017-07-06 15:12 UTC, amirkarimi commented
After having a discussion with @carlpulley we decided to keep the current PR at this state and create a new ticket to solve the issue: https://cakesolutions.jira.com/browse/CO-143

2017-07-06 16:42 UTC, carlpulley requested changes

2017-07-06 16:42 UTC, carlpulley commented on build.sbt
> +// These are dependency overrides which are different than the regular dependencies and should be maintained here. Note: Ideally we should refactor all dependencies in a single place. Read more: http
This line length is too long

2017-07-06 16:42 UTC, carlpulley commented on project/CakeDependencies.scala
> +
Delete extra line please

2017-07-06 16:42 UTC, carlpulley commented on src/main/scala/net/cakesolutions/CakePlatformPlugin.scala
> +  * Note: Ideally we should refactor all dependencies in a single place. Read more: https://cakesolutions.jira.com/browse/CO-143
Let's make this a TODO: with just the ticket number?

2017-07-06 16:42 UTC, carlpulley commented on project/CakeDependencies.scala
> +  * Note: Ideally we should refactor all dependencies in a single place. Read more: https://cakesolutions.jira.com/browse/CO-143
Please make a TODO

2017-07-06 16:42 UTC, carlpulley commented on project/project/CakePluginDependencies.scala
> +  * Note: Ideally we should refactor all dependencies in a single place. Read more: https://cakesolutions.jira.com/browse/CO-143
Please make a TODO

2017-07-06 16:53 UTC, carlpulley approved these changes

2017-07-07 08:21 UTC, ferhtaydn approved these changes

2017-07-07 09:22 UTC, merged