remove play dependencies from sbt-cake (
cakesolutions/sbt-cake pull request #35
Opened 2017-07-17 09:25 UTC by Slakah

Used by: cakesolutions/play-scala-template.g8#34

- [ ] Remove play dependencies from sbt-cake

2017-07-17 12:00 UTC, carlpulley requested changes

2017-07-17 12:00 UTC, carlpulley commented on project/project/CakePlatformDependencies.scala
>      val packager: ModuleID =
We also want to remove a number of the other Play related dependencies here - e.g. webjars grouping, janino(?), playJson, sbt-js-engine and sbt-web.

2017-07-17 12:28 UTC, Slakah commented on project/project/CakePlatformDependencies.scala
>      val packager: ModuleID =
playJson is currently only used for `akka-http` and I think janino is mainly used for colouring log output (correct me if I'm wrong).

I will remove the others.

2017-07-17 12:51 UTC, carlpulley commented on project/project/CakePlatformDependencies.scala
>      val packager: ModuleID =
The akka-http template is using spray-json, so it sounds like we can drop the playJson dependency (assuming that the play template has no need of it).

janino is currently only used in play template for colouring. Again, akka-http is not using this, so perhaps we should move this to the play template?

2017-07-17 13:17 UTC, carlpulley approved these changes

2017-07-17 13:18 UTC, carlpulley commented
We need to just check that this PR builds successfully in Jenkins before we can merge it.

2017-07-18 13:42 UTC, ferhtaydn commented
@Slakah I think you need to fix sbt-scripted tests in `sbt-test/sbt-cake/simple/build.sbt` has enablePlay keyword even you removed from sbt-cake to make jenkins happy. then we can merge that. /cc @carlpulley

2017-07-18 13:52 UTC, Slakah commented
@ferhtaydn, removed in 8d51d0778b4fe196ae9382e9245ef0a8cfbd9468, did a quick sanity grep as well `grep -r "enablePlay" .`.

2017-07-18 14:47 UTC, merged